owner: snapwiki
repo: SnapWikiUptime 

sites:
  - name: Snap! Wiki
    url: https://snapwiki.miraheze.org


status-website:
  baseUrl: /SnapWikiUptime
  logoUrl: https://snapwiki.github.io/assets/images/logo.png
  name: Snap! Wiki
  introTitle: "The Unofficial Wiki For Snappers, about Snap!"
  introMessage: This is a realtime status page for the Snap! Wiki
  navbar:
    - title: Home
      href: /SnapWikiUptime
    - title: Main Site
      href: https://snapwiki.github.io
    - title: Wiki
      href: https://snapwiki.miraheze.org
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
notifications:
  - type: discord
  
i18n:
  allSystemsOperational: All systems are operational
# See https://upptime.js.org/docs/configuration
workflowSchedule:
  uptime: "*/9 * * * *"
